<script setup lang="ts">
import{onMounted,ref}from'vue';import MovementCard from'../components/MovementCard.vue';import{movementsApi}from'../api';import type{Direction,MovementStatus,MovementSummary}from'../types';import{today}from'../utils/time';
const rows=ref<MovementSummary[]>([]),loading=ref(false),from=ref(today()),to=ref(today()),direction=ref<Direction|''>(''),status=ref<MovementStatus>('ACTIVE'),q=ref(''),missingPhoto=ref<boolean|undefined>(),hasIssue=ref<boolean|undefined>();
async function load(){loading.value=true;try{rows.value=(await movementsApi.list({from:from.value,to:to.value,direction:direction.value||undefined,status:status.value||undefined,missingPhoto:missingPhoto.value,hasIssue:hasIssue.value,q:q.value,size:100})).content}finally{loading.value=false}}
function preset(kind:'today'|'week'){const d=new Date();if(kind==='today'){from.value=to.value=today()}else{const day=(d.getDay()+6)%7;const monday=new Date(d);monday.setDate(d.getDate()-day);from.value=monday.toISOString().slice(0,10);to.value=today()}load()}
onMounted(load);
</script>
<template><div class="page"><h1 class="page-title">历史记录</h1><p class="page-lead">按实际流转时间查询。</p><section class="filters card card-pad"><div class="preset"><button class="btn btn-secondary" @click="preset('today')">今天</button><button class="btn btn-secondary" @click="preset('week')">本周</button></div><div class="grid-2"><div class="field"><label>开始日期</label><input class="input" type="date" v-model="from"/></div><div class="field"><label>结束日期</label><input class="input" type="date" v-model="to"/></div></div><div class="field"><label>搜索</label><input class="input" v-model.trim="q" placeholder="产品、Batch、Manufacture Lot、记录编号" @keyup.enter="load"/></div><div class="grid-2"><div class="field"><label>方向</label><select class="select" v-model="direction"><option value="">全部方向</option><option value="WAREHOUSE_TO_PRODUCTION">仓库 → 生产车间</option><option value="PRODUCTION_TO_WAREHOUSE">生产车间 → 仓库</option></select></div><div class="field"><label>状态</label><select class="select" v-model="status"><option value="ACTIVE">正常记录</option><option value="VOID">已作废</option></select></div></div><div class="grid-2"><label class="check"><input type="checkbox" v-model="missingPhoto" :true-value="true" :false-value="undefined"/>只看缺少照片</label><label class="check"><input type="checkbox" v-model="hasIssue" :true-value="true" :false-value="undefined"/>只看有异常</label></div><button class="btn btn-primary btn-block" @click="load">查询记录</button></section><section class="section"><div class="section-head"><h2 class="section-title">查询结果</h2><span class="hint">{{rows.length}} 条</span></div><div v-if="loading" class="card empty">正在查询…</div><div v-else-if="!rows.length" class="card empty">没有符合条件的记录。</div><div v-else class="stack"><MovementCard v-for="row in rows" :key="row.id" :movement="row"/></div></section></div></template>
<style scoped>.filters{display:grid;gap:13px}.preset{display:flex;gap:8px}.preset .btn{min-height:42px}.check{min-height:44px;display:flex;align-items:center;gap:8px;font-size:14px}.check input{width:18px;height:18px;accent-color:#174a68}</style>
