<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { productionTasksApi } from "../api";
import { errorMessage } from "../api/http";
import { useAuth } from "../auth";
import type { ProductionTask, ProductionTaskStatus } from "../types";
import { directionLabel } from "../utils/labels";
import ProductionTaskForm from "../components/ProductionTaskForm.vue";
import ProductionTaskTargets from "../components/ProductionTaskTargets.vue";
import { showDateTime } from "../utils/time";
const id=Number(useRoute().params.id),task=ref<ProductionTask>(),message=ref("");const{authenticated}=useAuth();
const editing=ref(false);
function saved(value:ProductionTask){task.value=value;editing.value=false}
const labels:Record<ProductionTaskStatus,string>={PREPARING:'备料中',IN_PROGRESS:'生产中',COMPLETED:'已完成',CANCELLED:'已取消'};
async function load(){try{task.value=await productionTasksApi.detail(id)}catch(e){message.value=errorMessage(e)}}
async function setStatus(status:ProductionTaskStatus){try{task.value=await productionTasksApi.status(id,status)}catch(e){message.value=errorMessage(e)}}
onMounted(load);
</script>
<template><div class="page"><p v-if="message" class="form-alert">{{message}}</p><div v-if="!task" class="card empty">正在读取生产任务…</div><template v-else><div class="task-head"><div><span class="status neutral">{{labels[task.status]}}</span><h1 class="page-title">{{task.productName}}</h1><p class="page-lead mono">{{task.batchNo}} · 计划 {{task.plannedDate}}</p></div><div class="completion"><strong>{{task.progressPercent}}%</strong><span>备料进度</span></div></div><ProductionTaskForm v-if="editing" :task="task" @saved="saved" @cancel="editing=false" /><section v-else class="card card-pad"><ProductionTaskTargets :targets="task.targets" /><p class="hint progress-note">缺料按所需数量减去净发料计算，净发料为已发料减去已退料。仅统计关联此任务的有效记录，不代表仓库库存。</p></section><p v-if="task.remarks" class="remark">{{task.remarks}}</p>
<section class="section"><div class="section-head"><h2 class="section-title">关联流转记录</h2><span class="hint">{{task.movements.length}} 条 · {{task.returnMovementCount}} 条退料 · {{task.issueMovementCount}} 条异常</span></div><div v-if="!task.movements.length" class="card empty">新增流转记录时选择此任务，记录会显示在这里。</div><div v-else class="movement-list"><RouterLink v-for="m in task.movements" :key="m.id" :to="`/movements/${m.id}`" class="movement-row card"><div><strong>{{m.recordNo}}</strong><span>{{directionLabel(m.direction)}}<template v-if="m.returnMovement"> · 退回</template> · {{showDateTime(m.movementTime)}}</span><small>{{m.productNames.join('、')}}</small></div><b>{{m.totalCartons}} 箱 · {{m.totalQuantity.toLocaleString()}} 个</b><span class="arrow">›</span></RouterLink></div></section>
<section v-if="authenticated && !editing" class="section actions"><button class="btn btn-secondary" @click="editing=true">编辑所需物料</button><button v-if="task.status==='PREPARING'" class="btn btn-primary" @click="setStatus('IN_PROGRESS')">开始生产</button><button v-if="task.status==='IN_PROGRESS'" class="btn btn-primary" @click="setStatus('COMPLETED')">标记已完成</button><button v-if="task.status!=='COMPLETED'&&task.status!=='CANCELLED'" class="btn btn-secondary" @click="setStatus('CANCELLED')">取消任务</button><button v-if="task.status==='COMPLETED'||task.status==='CANCELLED'" class="btn btn-secondary" @click="setStatus('IN_PROGRESS')">重新开启</button></section></template></div></template>
<style scoped>.progress-note{margin:16px 0 0}.page-title{overflow-wrap:anywhere}.task-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.completion{text-align:right;color:#267566}.completion strong{display:block;font-size:32px;line-height:1}.completion span{font-size:12px}.overview{position:relative;display:grid;grid-template-columns:repeat(3,1fr);gap:12px;overflow:hidden}.overview>div{display:grid;gap:5px}.overview small{color:#66747c}.overview b{font-size:17px}.bar{position:absolute;left:0;right:0;bottom:0;height:5px;background:#e5ecee}.bar i{display:block;height:100%;background:#267566}.remark{padding:12px;background:#f3f7f8;border-radius:8px}.movement-list{display:grid;gap:9px}.movement-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:12px;padding:12px 14px}.movement-row>div{display:grid;gap:3px}.movement-row span,.movement-row small{color:#66747c;font-size:12px}.movement-row>b{font-size:13px}.arrow{font-size:24px}.actions{display:flex;flex-wrap:wrap;gap:9px}.form-alert{color:#8f1d25}@media(max-width:520px){.overview{grid-template-columns:1fr}.movement-row{grid-template-columns:1fr auto}.movement-row>b{grid-column:1}.arrow{grid-column:2;grid-row:1/3}}</style>
